### ISSUE TITLE
Frequent error messages from lsp status for latest nvim. 

### ISSUE THREAD

**Issue by shivanthzen** [wbthomason/lsp-status.nvim#79] opened 2022-06-15 16:13 UTC
![Screenshot 2022-06-16 at 12 11 55 AM](https://user-images.githubusercontent.com/92778810/173875297-9e6d7a7b-b7c8-4900-a1f0-ee5c0586caec.png)

NVIM v0.8.0-dev+391-gc5720c722
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by joleeee** [comment] 2022-06-29 10:47
This happens for me on NVIM v0.7.2 aswell

As a workaround until #80 gets merged or the issue is otherwise fixed, you can use rust_analyzer version 2022-05-30, if you use lsp-install then simply
```vim
:LspInstall rust_analyzer@2022-05-30
```
Edit: assuming your issue is related to rust_analyzer, like it was for me

**Closed as completed** 2022-08-03 00:18 UTC
